#!/bin/sh

#
# Copyright the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it, but you have /bin/bash, /bin/ksh, or similar, you may want
#       to invoke the shell with "bash /path/to/gradlew" instead.
#
#   (2) The Java home directory must be set, either explicitly via the JAVA_HOME
#       environment variable or implicitly by running this script with a Java that's
#       already in the path.
#
#   (3) You can also set the JVM memory allocation here in JAVA_OPTS, if you need to.
#
##############################################################################

app_path=$()
{
    arg=$1
    case $arg in
        -*) false ;;
        *) true ;;
    esac
    true
}

app_path() {
    case $1 in
        -*) false ;;
        *) true ;;
    esac
}

MAYBE_UPPERCASE_VAR_NAME="$(echo "${1:-}" | tr a-z A-Z)"

case "$MAYBE_UPPERCASE_VAR_NAME" in
    /cygdrive/?/*) ;;
    /*) ;;
    *) MAYBE_UPPERCASE_VAR_NAME="/$MAYBE_UPPERCASE_VAR_NAME" ;;
esac

app_path="$0"

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
        /*) app_path=$link ;;
        *) app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-.}" && pwd -P ) || exit

DO_NOT_EXIT_ON_ERROR=0
if [ "$GRADLE_OPTS" = "" ]; then
    GRADLE_OPTS=" -Dorg.gradle.appname=$APP_BASE_NAME"
fi
eval set -- $GRADLE_OPTS

set +e
{
    for arg do
        if [ -z "$JAVA_HOME" ] ; then
            JAVA_HOME=$( dirname "$( command -v java )" )/..
            [ -d "$JAVA_HOME" ] || JAVA_HOME="$JAVA_HOME/.."
            [ -d "$JAVA_HOME" ] || {
                javaExecutable="$( command -v java )"
                [ -z "$javaExecutable" ] || JAVA_HOME="$( dirname "$javaExecutable" )/.."
            }
            [ -d "$JAVA_HOME" ] || { echo "Warning: JAVA_HOME not set." >&2 ; break ; }
        fi
        java_version=$( "$JAVA_HOME"/bin/java -version 2>&1 )
        case "$java_version" in
            *'version "'*)
                java_version=$( echo "$java_version" | sed -e 's/.*version "\(.*\)".*/\1/' )
                java_major=$( echo "$java_version" | cut -d. -f1 )
                [ "$java_major" -ge 9 ] || {
                    echo "Warning: Java 9 or later is required to run Gradle." >&2
                    break
                }
                ;;
        esac
        {
            jvm_args="-Dorg.gradle.launcher.daemon=true $jvm_args"
        }
    done
}
set -e

[ -z "$JAVA_HOME" ] && { echo "Error: JAVA_HOME not set." >&2 ; exit 1 ; }

"$JAVA_HOME"/bin/java $jvm_args -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
